#!/bin/sh

function usage {
	cat << EOF

指定したブランチをREMOTEから取得します

require:
    peco

Usage:
	$(basename ${0}) pr-number 

EOF
}

cd `pwd`/`git rev-parse --show-cdup`

NUMBER=${1:-`gh pr list | fzf | head -n 1 | cut -f1`}

gh pr checkout ${NUMBER}
