#!/bin/sh

function usage {
	cat << EOF

現在のブランチをREMOTEにpushします

Usage:
	$(basename ${0}) [remote]

EOF
}

# check argment count
if [ $# -lt 0 ]; then
    usage
    exit 0
fi

cd `pwd`/`git rev-parse --show-cdup`

REMOTE=${1:-"origin"}
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

git push $REMOTE $BRANCH_NAME
git status
