#!/bin/sh

function usage {
	cat << EOF

指定したブランチをREMOTEから取得します

require:
    peco

Usage:
	$(basename ${0}) <branch> [remote]

EOF
}

cd `pwd`/`git rev-parse --show-cdup`

BRANCH=${1:-`git branch -r| peco --prompt "GIT BRANCH>" | head -n 1 | sed -e "s/^\*\s*//g"`}
REMOTE=${2:-"origin"}

git fetch
git checkout -b ${BRANCH} ${REMOTE}/${BRANCH}

